// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatBufferData
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FBUIPopup : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static FBUIPopup GetRootAsFBUIPopup(ByteBuffer _bb) { return GetRootAsFBUIPopup(_bb, new FBUIPopup()); }
  public static FBUIPopup GetRootAsFBUIPopup(ByteBuffer _bb, FBUIPopup obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FBUIPopup __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Idx { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Type { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetTypeBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetTypeBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetTypeArray() { return __p.__vector_as_array<byte>(6); }
  public string PrefabPath { get { int o = __p.__offset(8); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetPrefabPathBytes() { return __p.__vector_as_span<byte>(8, 1); }
#else
  public ArraySegment<byte>? GetPrefabPathBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public byte[] GetPrefabPathArray() { return __p.__vector_as_array<byte>(8); }

  public static Offset<FlatBufferData.FBUIPopup> CreateFBUIPopup(FlatBufferBuilder builder,
      int Idx = 0,
      StringOffset TypeOffset = default(StringOffset),
      StringOffset PrefabPathOffset = default(StringOffset)) {
    builder.StartTable(3);
    FBUIPopup.AddPrefabPath(builder, PrefabPathOffset);
    FBUIPopup.AddType(builder, TypeOffset);
    FBUIPopup.AddIdx(builder, Idx);
    return FBUIPopup.EndFBUIPopup(builder);
  }

  public static void StartFBUIPopup(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddIdx(FlatBufferBuilder builder, int idx) { builder.AddInt(0, idx, 0); }
  public static void AddType(FlatBufferBuilder builder, StringOffset typeOffset) { builder.AddOffset(1, typeOffset.Value, 0); }
  public static void AddPrefabPath(FlatBufferBuilder builder, StringOffset prefabPathOffset) { builder.AddOffset(2, prefabPathOffset.Value, 0); }
  public static Offset<FlatBufferData.FBUIPopup> EndFBUIPopup(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatBufferData.FBUIPopup>(o);
  }
}


static public class FBUIPopupVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Idx*/, 4 /*int*/, 4, false)
      && verifier.VerifyString(tablePos, 6 /*Type*/, false)
      && verifier.VerifyString(tablePos, 8 /*PrefabPath*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
