// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatBufferData
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FBUnitMonsterRoot : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static FBUnitMonsterRoot GetRootAsFBUnitMonsterRoot(ByteBuffer _bb) { return GetRootAsFBUnitMonsterRoot(_bb, new FBUnitMonsterRoot()); }
  public static FBUnitMonsterRoot GetRootAsFBUnitMonsterRoot(ByteBuffer _bb, FBUnitMonsterRoot obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyFBUnitMonsterRoot(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, FBUnitMonsterRootVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FBUnitMonsterRoot __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FlatBufferData.FBUnitMonster? Entries(int j) { int o = __p.__offset(4); return o != 0 ? (FlatBufferData.FBUnitMonster?)(new FlatBufferData.FBUnitMonster()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int EntriesLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<FlatBufferData.FBUnitMonsterRoot> CreateFBUnitMonsterRoot(FlatBufferBuilder builder,
      VectorOffset entriesOffset = default(VectorOffset)) {
    builder.StartTable(1);
    FBUnitMonsterRoot.AddEntries(builder, entriesOffset);
    return FBUnitMonsterRoot.EndFBUnitMonsterRoot(builder);
  }

  public static void StartFBUnitMonsterRoot(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddEntries(FlatBufferBuilder builder, VectorOffset entriesOffset) { builder.AddOffset(0, entriesOffset.Value, 0); }
  public static VectorOffset CreateEntriesVector(FlatBufferBuilder builder, Offset<FlatBufferData.FBUnitMonster>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateEntriesVectorBlock(FlatBufferBuilder builder, Offset<FlatBufferData.FBUnitMonster>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEntriesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<FlatBufferData.FBUnitMonster>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEntriesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<FlatBufferData.FBUnitMonster>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartEntriesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<FlatBufferData.FBUnitMonsterRoot> EndFBUnitMonsterRoot(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatBufferData.FBUnitMonsterRoot>(o);
  }
  public static void FinishFBUnitMonsterRootBuffer(FlatBufferBuilder builder, Offset<FlatBufferData.FBUnitMonsterRoot> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedFBUnitMonsterRootBuffer(FlatBufferBuilder builder, Offset<FlatBufferData.FBUnitMonsterRoot> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class FBUnitMonsterRootVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Entries*/, FlatBufferData.FBUnitMonsterVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
