// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatBufferData
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct FBUnitCharacterRoot : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static FBUnitCharacterRoot GetRootAsFBUnitCharacterRoot(ByteBuffer _bb) { return GetRootAsFBUnitCharacterRoot(_bb, new FBUnitCharacterRoot()); }
  public static FBUnitCharacterRoot GetRootAsFBUnitCharacterRoot(ByteBuffer _bb, FBUnitCharacterRoot obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool VerifyFBUnitCharacterRoot(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("", false, FBUnitCharacterRootVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FBUnitCharacterRoot __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FlatBufferData.FBUnitCharacter? Entries(int j) { int o = __p.__offset(4); return o != 0 ? (FlatBufferData.FBUnitCharacter?)(new FlatBufferData.FBUnitCharacter()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int EntriesLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<FlatBufferData.FBUnitCharacterRoot> CreateFBUnitCharacterRoot(FlatBufferBuilder builder,
      VectorOffset entriesOffset = default(VectorOffset)) {
    builder.StartTable(1);
    FBUnitCharacterRoot.AddEntries(builder, entriesOffset);
    return FBUnitCharacterRoot.EndFBUnitCharacterRoot(builder);
  }

  public static void StartFBUnitCharacterRoot(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddEntries(FlatBufferBuilder builder, VectorOffset entriesOffset) { builder.AddOffset(0, entriesOffset.Value, 0); }
  public static VectorOffset CreateEntriesVector(FlatBufferBuilder builder, Offset<FlatBufferData.FBUnitCharacter>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateEntriesVectorBlock(FlatBufferBuilder builder, Offset<FlatBufferData.FBUnitCharacter>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEntriesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<FlatBufferData.FBUnitCharacter>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateEntriesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<FlatBufferData.FBUnitCharacter>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartEntriesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<FlatBufferData.FBUnitCharacterRoot> EndFBUnitCharacterRoot(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatBufferData.FBUnitCharacterRoot>(o);
  }
  public static void FinishFBUnitCharacterRootBuffer(FlatBufferBuilder builder, Offset<FlatBufferData.FBUnitCharacterRoot> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedFBUnitCharacterRootBuffer(FlatBufferBuilder builder, Offset<FlatBufferData.FBUnitCharacterRoot> offset) { builder.FinishSizePrefixed(offset.Value); }
}


static public class FBUnitCharacterRootVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfTables(tablePos, 4 /*Entries*/, FlatBufferData.FBUnitCharacterVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
